# coding:utf-8
UNIQUE_BY_ACCOUNT = True
DAY_INDEX = 1
FIRST_DAY = 7
FINAL_DAY = 13
FILTER_BY_DAY_NAME = 'filter_by_day.log'
DAY_SCORE = r''
GUILD_TRAIN_NAME = r''
SYS_LOG_NAME = r''
ROOT_NAME = r'E:\shLog\tlog'
INNER_FILTER_NAME = r'E:\shLog\tlog\dev_openids.txt'
OUT_FILTER_NAME = r''
DATA_FOLDER = r'E:\trunk_server\kbengine\assets\scripts\data'
GUILD_TRAIN_TABLE = ''
MAX_LEFT_LEVEL = 11
ORI_FILE_NAME_LIST = [r'F:\shdownload\log\9.150.94.241_data_home_user00_xzj_kbengine_assets_logs_xzj.log.3']
OPEN_IDS_TXT = r'E:\shLog\tlog\openids.txt'
# SEX_FILE = 'sex.txt'
# PLAYER_11_file = r'11-11.txt'
